export const MENU = [
  ['tea', 'Tea', 'Breakfast', 12, 'A warm, comforting cup'],
  ['vada-pav', 'Vada Pav', 'Breakfast', 20, 'Mumbai-style spiced potato slider'],
  ['upma', 'Upma', 'Breakfast', 25, 'South Indian savoury breakfast'],
  ['bread-pattice', 'Bread Pattice', 'Breakfast', 20, 'Crisp, golden and filling'],
  ['poha', 'Poha', 'Breakfast', 25, 'Light, lemony and satisfying'],
  ['appe', 'Appe', 'Breakfast', 30, 'Soft bite-sized breakfast treats'],
  ['sabudana-khichadi', 'Sabudana Khichadi', 'Breakfast', 35, 'Classic Maharashtrian comfort food'],
  ['sabudana-vada', 'Sabudana Vada (3 pcs)', 'Breakfast', 60, 'Three crunchy tapioca fritters'],
  ['batata-vada-sambar-single', 'Batata Vada Sambar (Single)', 'Breakfast', 25, 'Potato fritter with sambar'],
  ['batata-vada-sambar-double', 'Batata Vada Sambar (Double)', 'Breakfast', 50, 'Two potato fritters with sambar'],
  ['misal-pav', 'Misal Pav', 'Breakfast', 60, 'Spicy sprout curry with pav'],
  ['omelette-pav', 'Omelette Pav', 'Breakfast', 60, 'Masala omelette with pav'],
  ['egg-bhurji', 'Egg Bhurji (Double Egg)', 'Breakfast', 80, 'Two eggs scrambled with masala'],
  ['boiled-egg', 'Boiled Egg (Single)', 'Breakfast', 15, 'Simple, protein-rich and fresh'],
  ['extra-pav', 'Extra Pav', 'Breakfast', 5, 'Add one more pav'],

  ['cold-coffee', 'Cold Coffee', 'Cold Beverages', 40, 'Chilled coffee, smooth and refreshing'],
  ['thick-coffee', 'Thick Coffee', 'Cold Beverages', 50, 'Rich, creamy cold coffee'],
  ['cold-chocolate', 'Cold Chocolate', 'Cold Beverages', 60, 'Chilled chocolate drink'],
  ['thick-with-crush', 'Thick with Crush', 'Cold Beverages', 60, 'Thick cold drink with fruit crush'],
  ['thick-with-ice-cream', 'Thick with Ice Cream', 'Cold Beverages', 70, 'Thick drink topped with ice cream'],
  ['thick-with-dry-fruits', 'Thick with Dry Fruits', 'Cold Beverages', 80, 'Thick drink with dry fruits'],

  ['black-coffee', 'Black Coffee', 'Hot Beverages', 20, 'Bold and freshly brewed'],
  ['hot-coffee', 'Hot Coffee', 'Hot Beverages', 30, 'A comforting hot coffee'],
  ['bornvita', 'Bornvita', 'Hot Beverages', 40, 'Warm malted chocolate drink'],
  ['hazelnut-coffee', 'Hazelnut Coffee', 'Hot Beverages', 50, 'Coffee with hazelnut flavour'],
  ['caramel-coffee', 'Caramel Coffee', 'Hot Beverages', 50, 'Coffee with caramel sweetness'],
  ['irish-coffee', 'Irish Coffee', 'Hot Beverages', 50, 'Smooth coffee with Irish flavour'],

  ['oreo-shake', 'Oreo Shake', 'Thick Shakes', 60, 'Creamy shake with Oreo'],
  ['kit-kat-shake', 'Kit Kat Shake', 'Thick Shakes', 60, 'Creamy shake with Kit Kat'],
  ['black-current-shake', 'Black Current Shake', 'Thick Shakes', 60, 'Fruity black currant shake'],
  ['strawberry-shake', 'Strawberry Shake', 'Thick Shakes', 60, 'Classic strawberry shake'],
  ['mango-shake', 'Mango Shake', 'Thick Shakes', 70, 'Rich seasonal mango shake'],

  ['veg-burger', 'Veg Burger', 'Burgers', 59, 'Crispy vegetable patty burger'],
  ['cheese-burger', 'Cheese Burger', 'Burgers', 69, 'Veg burger with cheese'],
  ['double-decker-burger', 'Double Decker Burger', 'Burgers', 89, 'A generous double-layer burger'],
  ['paneer-cheese-burger', 'Paneer Cheese Burger', 'Burgers', 99, 'Paneer and cheese burger'],

  ['margarita-pizza', 'Margarita Pizza', 'Pizzas', 100, 'Classic tomato and cheese pizza'],
  ['fresh-veggie-pizza', 'Fresh Veggie Pizza', 'Pizzas', 110, 'Pizza loaded with fresh vegetables'],
  ['onion-capsicum-pizza', 'Onion + Capsicum Pizza', 'Pizzas', 120, 'Onion and capsicum topping'],
  ['corn-cheese-pizza', 'Corn Cheese Pizza', 'Pizzas', 120, 'Sweet corn with melted cheese'],
  ['paneer-delight-pizza', 'Paneer Delight', 'Pizzas', 140, 'Paneer-packed cheesy pizza'],
  ['paneer-peri-peri-pizza', 'Paneer Peri Peri Pizza', 'Pizzas', 160, 'Paneer with peri peri spice'],
  ['paneer-makhani-pizza', 'Paneer Makhani Pizza', 'Pizzas', 170, 'Paneer with rich makhani flavour'],
  ['tandoor-paneer-pizza', 'Tandoor Paneer Pizza', 'Pizzas', 180, 'Tandoori paneer pizza'],
  ['cheese-burst-pizza', 'Cheese Burst Pizza', 'Pizzas', 210, 'Extra-cheesy cheese burst pizza'],

  ['veg-sandwich', 'Veg Sandwich', 'Sandwich', 70, 'Fresh vegetable sandwich'],
  ['chutney-fusion-sandwich', 'Chutney Fusion Sandwich', 'Sandwich', 90, 'Sandwich with a chutney fusion'],
  ['veg-cheese-club-sandwich', 'Veg Cheese Club Sandwich', 'Sandwich', 100, 'Layered vegetable and cheese sandwich'],
  ['veg-cheese-grilled-sandwich', 'Veg Cheese Grilled Sandwich', 'Sandwich', 100, 'Grilled vegetable cheese sandwich'],
  ['paneer-mustard-sandwich', 'Paneer Mustard Sandwich', 'Sandwich', 110, 'Paneer with mustard flavour'],
  ['paneer-peri-peri-sandwich', 'Paneer Peri Peri Sandwich', 'Sandwich', 110, 'Paneer with peri peri spice'],
  ['corn-cheese-sandwich', 'Corn Cheese Sandwich', 'Sandwich', 110, 'Sweet corn and cheese sandwich'],
  ['corn-spinach-sandwich', 'Corn Spinach Sandwich', 'Sandwich', 110, 'Corn and spinach sandwich'],
  ['paneer-grilled-sandwich', 'Paneer Grilled Sandwich', 'Sandwich', 120, 'Grilled paneer sandwich'],
  ['bombay-masala-sandwich', 'Bombay Masala Sandwich', 'Sandwich', 130, 'Classic Bombay masala sandwich'],
  ['paneer-makhani-sandwich', 'Paneer Makhani Sandwich', 'Sandwich', 140, 'Paneer with makhani flavour'],
  ['nepolian-sandwich', 'Nepolian Sandwich', 'Sandwich', 140, 'A loaded café-style sandwich'],
  ['farm-house-grilled-sandwich', 'Farm House Grilled Sandwich', 'Sandwich', 150, 'Loaded grilled vegetable sandwich'],
  ['chocolate-cheese-sandwich', 'Chocolate Cheese Sandwich', 'Sandwich', 160, 'Sweet chocolate and cheese sandwich'],
  ['tandoori-paneer-sandwich', 'Tandoor Paneer Sandwich', 'Sandwich', 140, 'Tandoori paneer sandwich'],

  ['garlic-toast', 'Garlic Toast', 'Bread Toast', 110, 'Toasted bread with garlic'],
  ['cheese-toast', 'Cheese Toast', 'Bread Toast', 120, 'Toasted bread with cheese'],
  ['cheese-chilli-toast', 'Cheese Chilli Toast', 'Bread Toast', 140, 'Cheese toast with chilli'],

  ['small-combo', 'Small Combo', 'Combos', 159, 'Veg burger · salted fries · hot coffee'],
  ['maggie-combo', 'Maggie Combo', 'Combos', 149, 'Vegetable maggie · cheese masala maggie · hot coffee'],
  ['cafe-special', 'Cafe Special', 'Combos', 199, 'Veg sandwich · green apple mojito · peri peri fries'],
  ['friendship-combo', 'Friendship Combo', 'Combos', 319, 'Cheese burger · virgin mojito · masala maggie · salted fries · veg cheese grilled sandwich'],
  ['family-combo', 'Family Combo (For 8 People)', 'Combos', 999, 'White cheese pasta · extra cheese corn momos · cheese peri peri maggie · tandoor paneer pizza · paneer grilled cheese sandwich · cheese toast · cheese burger · thick coffee (4)'],
  ['cheesy-combo', 'Cheesy Combo', 'Combos', 549, 'Thick coffee · corn cheese pizza · cheese toast · veg cheese momos · white cheese pasta'],
].map(([id, name, category, price, description]) => ({ id, name, category, price, description, available: true }))
