export const MENU = [
  ['gold-flake-kings-red', 'Gold Flake Kings Red', 'Cigarettes', 24, 'Sold individually'],
  ['gold-flake-kings-blue-lights', 'Gold Flake Kings Blue / Lights', 'Cigarettes', 24, 'Sold individually'],
  ['classic-milds', 'Classic Milds', 'Cigarettes', 24, 'Sold individually'],
  ['classic-regular', 'Classic Regular', 'Cigarettes', 24, 'Sold individually'],
  ['classic-ultra-milds', 'Classic Ultra Milds', 'Cigarettes', 24, 'Sold individually'],
  ['classic-ice-burst', 'Classic Ice Burst', 'Cigarettes', 24, 'Sold individually'],
  ['marlboro-red', 'Marlboro Red', 'Cigarettes', 24, 'Sold individually'],
  ['marlboro-fuse-beyond', 'Marlboro Fuse Beyond', 'Cigarettes', 24, 'Sold individually'],
  ['american-club-ny-cool', 'American Club NY Cool', 'Cigarettes', 18, 'Sold individually'],
  ['stellar-define-millennium', 'Stellar Define Millennium', 'Cigarettes', 18, 'Sold individually'],
  ['gold-flake-smart', 'Gold Flake Smart', 'Cigarettes', 12, 'Sold individually'],
  ['gold-flake-blue-optima', 'Gold Flake Blue Optima', 'Cigarettes', 18, 'Sold individually'],
  ['classic-optima-variants', 'Classic Optima variants', 'Cigarettes', 18, 'Sold individually'],
  ['classic-connect', 'Classic Connect', 'Cigarettes', 22, 'Sold individually'],

  ['cold-coffee', 'Cold Coffee', 'Cold Beverages', 50, ''],
  ['thick-coffee', 'Thick Coffee', 'Cold Beverages', 60, ''],
  ['cold-chocolate', 'Cold Chocolate', 'Cold Beverages', 70, ''],
  ['thick-with-crush', 'Thick with Crush', 'Cold Beverages', 70, ''],
  ['thick-with-ice-cream', 'Thick with Ice Cream', 'Cold Beverages', 80, ''],
  ['thick-with-dry-fruits', 'Thick with Dry Fruits', 'Cold Beverages', 90, ''],

  ['black-coffee', 'Black Coffee', 'Hot Beverages', 20, ''],
  ['hot-coffee', 'Hot Coffee', 'Hot Beverages', 30, ''],
  ['bornvita', 'Bornvita', 'Hot Beverages', 50, ''],
  ['hazelnut-coffee', 'Hazelnut Coffee', 'Hot Beverages', 70, ''],
  ['caramel-coffee', 'Caramel Coffee', 'Hot Beverages', 70, ''],
  ['irish-coffee', 'Irish Coffee', 'Hot Beverages', 70, ''],

  ['oreo-shake', 'Oreo Shake', 'Thick Shakes', 60, ''],
  ['kit-kat-shake', 'Kit Kat Shake', 'Thick Shakes', 60, ''],
  ['black-current-shake', 'Black Current Shake', 'Thick Shakes', 60, ''],
  ['strawberry-shake', 'Strawberry Shake', 'Thick Shakes', 60, ''],
  ['mango-shake', 'Mango Shake', 'Thick Shakes', 70, ''],

  ['veg-burger', 'Veg Burger', 'Burgers', 59, ''],
  ['cheese-burger', 'Cheese Burger', 'Burgers', 69, ''],
  ['double-decker-burger', 'Double Decker Burger', 'Burgers', 89, ''],
  ['paneer-cheese-burger', 'Paneer Cheese Burger', 'Burgers', 99, ''],

  ['margarita-pizza', 'Margarita Pizza', 'Pizzas', 100, ''],
  ['fresh-veggie-pizza', 'Fresh Veggie Pizza', 'Pizzas', 110, ''],
  ['onion-capsicum-pizza', 'Onion + Capsicum Pizza', 'Pizzas', 120, ''],
  ['corn-cheese-pizza', 'Corn Cheese Pizza', 'Pizzas', 120, ''],
  ['paneer-delight-pizza', 'Paneer Delight', 'Pizzas', 140, ''],
  ['paneer-peri-peri-pizza', 'Paneer Peri Peri Pizza', 'Pizzas', 160, ''],
  ['paneer-makhani-pizza', 'Paneer Makhani Pizza', 'Pizzas', 170, ''],
  ['tandoor-paneer-pizza', 'Tandoor Paneer Pizza', 'Pizzas', 180, ''],
  ['cheese-burst-pizza', 'Cheese Burst Pizza', 'Pizzas', 210, ''],

  ['veg-sandwich', 'Veg Sandwich', 'Sandwich', 70, ''],
  ['chutney-fusion-sandwich', 'Chutney Fusion Sandwich', 'Sandwich', 90, ''],
  ['veg-cheese-club-sandwich', 'Veg Cheese Club Sandwich', 'Sandwich', 100, ''],
  ['veg-cheese-grilled-sandwich', 'Veg Cheese Grilled Sandwich', 'Sandwich', 100, ''],
  ['paneer-mustard-sandwich', 'Paneer Mustard Sandwich', 'Sandwich', 110, ''],
  ['paneer-peri-peri-sandwich', 'Paneer Peri Peri Sandwich', 'Sandwich', 110, ''],
  ['corn-cheese-sandwich', 'Corn Cheese Sandwich', 'Sandwich', 110, ''],
  ['corn-spinach-sandwich', 'Corn Spinach Sandwich', 'Sandwich', 110, ''],
  ['paneer-grilled-sandwich', 'Paneer Grilled Sandwich', 'Sandwich', 120, ''],
  ['bombay-masala-sandwich', 'Bombay Masala Sandwich', 'Sandwich', 130, ''],
  ['paneer-makhani-sandwich', 'Paneer Makhani Sandwich', 'Sandwich', 140, ''],
  ['nepolian-sandwich', 'Nepolian Sandwich', 'Sandwich', 140, ''],
  ['farm-house-grilled-sandwich', 'Farm House Grilled Sandwich', 'Sandwich', 150, ''],
  ['chocolate-cheese-sandwich', 'Chocolate Cheese Sandwich', 'Sandwich', 160, ''],
  ['tandoori-paneer-sandwich', 'Tandoor Paneer Sandwich', 'Sandwich', 140, ''],

  ['garlic-toast', 'Garlic Toast', 'Bread Toast', 110, ''],
  ['cheese-toast', 'Cheese Toast', 'Bread Toast', 120, ''],
  ['cheese-chilli-toast', 'Cheese Chilli Toast', 'Bread Toast', 140, ''],

  ['salted-fries', 'Salted Fries', 'Fries', 70, ''],
  ['masala-fries', 'Masala Fries', 'Fries', 80, ''],
  ['peri-peri-fries', 'Peri Peri Fries', 'Fries', 90, ''],
  ['cheesy-fries', 'Cheesy Fries', 'Fries', 130, ''],

  ['plain-maggie', 'Plain Maggie', 'Maggies', 60, ''],
  ['vegetable-maggie', 'Vegetable Maggie', 'Maggies', 70, ''],
  ['masala-maggie', 'Masala Maggie', 'Maggies', 70, ''],
  ['cheese-masala-maggie', 'Cheese Masala Maggie', 'Maggies', 80, ''],
  ['peri-peri-maggie', 'Peri Peri Maggie', 'Maggies', 90, ''],
  ['cheese-peri-peri-maggie', 'Cheese Peri Peri Maggie', 'Maggies', 120, ''],

  ['white-cheese-pasta', 'White Cheese Pasta', 'Pastas', 180, ''],
  ['red-sauce-pasta', 'Red Sauce Pasta', 'Pastas', 180, ''],

  ['paav-bhaji', 'Paav Bhaji', 'Paav Bhaji / Pulao', 110, ''],
  ['amul-paav-bhaji', 'Amul Paav Bhaji', 'Paav Bhaji / Pulao', 130, ''],
  ['cheese-paav-bhaji', 'Cheese Paav Bhaji', 'Paav Bhaji / Pulao', 160, ''],
  ['jain-paav-bhaji', 'Jain Paav Bhaji', 'Paav Bhaji / Pulao', 120, ''],
  ['veg-pulao', 'Veg Pulao', 'Paav Bhaji / Pulao', 110, ''],
  ['paneer-pulao', 'Paneer Pulao', 'Paav Bhaji / Pulao', 140, ''],
  ['tawa-pulao', 'Tawa Pulao', 'Paav Bhaji / Pulao', 140, ''],

  ['veg-momos', 'Veg Momos', 'Momos', 80, ''],
  ['veg-cheese-momos', 'Veg Cheese Momos', 'Momos', 90, ''],
  ['paneer-momos', 'Paneer Momos', 'Momos', 100, ''],
  ['veg-kurkure-momos', 'Veg Kurkure Momos', 'Momos', 110, ''],
  ['paneer-cheese-momos', 'Paneer Cheese Momos', 'Momos', 110, ''],
  ['paneer-corn-momos', 'Paneer Corn Momos', 'Momos', 110, ''],
  ['extra-cheese-corn-momos', 'Extra Cheese Corn Momos', 'Momos', 120, ''],

  ['virgin-mojito', 'Virgin Mojito', 'Mocktails', 89, ''],
  ['green-apple-mojito', 'Green Apple Mojito', 'Mocktails', 99, ''],
  ['water-melon', 'Water Melon', 'Mocktails', 99, ''],
  ['blue-lagoon', 'Blue Lagoon', 'Mocktails', 99, ''],

  ['lemon-ice-tea', 'Lemon Ice Tea', 'Ice Tea', 50, ''],
  ['peach-ice-tea', 'Peach Ice Tea', 'Ice Tea', 60, ''],

  ['tea', 'Tea', 'Hot Tea', 30, ''],
  ['black-tea', 'Black Tea', 'Hot Tea', 20, ''],
  ['ginger-lemon-tea', 'Ginger Lemon Tea', 'Hot Tea', 30, ''],
  ['bun-maska', 'Bun Maska', 'Hot Tea', 50, ''],

  ['bread-butter', 'Bread Butter', 'Snacks', 60, ''],
  ['omelette-toast', 'Omelette Toast', 'Snacks', 90, ''],
  ['omelette-sandwich', 'Omelette Sandwich', 'Snacks', 110, ''],
  ['boiled-egg-sandwich', 'Boiled Egg Sandwich', 'Snacks', 110, ''],
  ['bhurji-sandwich', 'Bhurji Sandwich', 'Snacks', 110, ''],

  ['small-combo', 'Small Combo', 'Combos', 149, 'Veg Burger 1 · Salted Fries 1 · Hot Coffee 1'],
  ['maggie-combo', 'Maggie Combo', 'Combos', 159, 'Vegetable Maggie 1 · Cheese Masala Maggie 1 · Hot Coffee 1'],
  ['cafe-special', 'Cafe Special', 'Combos', 239, 'Veg Sandwich 1 · Green Apple Mojito 1 · Peri Peri Fries 1'],
  ['friendship-combo', 'Friendship Combo', 'Combos', 349, 'Cheese Burger 1 · Virgin Mojito 1 · Masala Maggie 1 · Salted Fries 1 · Veg Cheese Grilled Sandwich 1'],
  ['family-combo', 'Family Combo (For 8 People)', 'Combos', 1049, 'White Cheese Pasta 1 · Extra Cheese Corn Momos 1 · Cheese Peri Peri Maggie 1 · Tandoor Paneer Pizza 1 · Paneer Grilled Sandwich 1 · Cheese Toast 1 · Cheese Burger 1 · Thick Coffee 4'],
  ['cheesy-combo', 'Cheesy Combo', 'Combos', 549, 'Thick Coffee 1 · Corn Cheese Pizza 1 · Cheese Toast 1 · Veg Cheese Momos 1 · White Cheese Pasta 1'],
].map(([id, name, category, price, description]) => ({ id, name, category, price, description, available: true }))
